# Generated by Django 3.2.19 on 2024-08-29 06:46

import Dish.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishName', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('dishImage', models.ImageField(blank=True, null=True, upload_to=Dish.models.dishImagePath)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.categorymodel')),
            ],
        ),
    ]
