# Say the number generated by the computer is 1038. An example interaction could look like this:
#   Welcome to the Cows and Bulls Game! 
#   Enter a number: 
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1216
#   1 cow, 1 bull


import random
num = str(random.randint(1000,9999))
cow = 0
bull = 0
print(num)
count = 0

my_string = "Hello 0World"
n =8

my_string = my_string[:n] + my_string[n+1:]

print(my_string)



history = {}
while(cow != 4):
    
    count += 1
    guessNum = input("Guess the 4 digit number : ")
    

    cow = 0
    bull = 0
    for i in range(4):
        my_string = num[:i] + num[i+1:]

        # print(my_string , my_string.__contains__(guessNum[i]), guessNum[i])

        if num[i] == guessNum[i]:
            cow += 1
        elif my_string.__contains__(guessNum[i]):
            bull += 1

    cowBull = f'{cow}  Cow ,{bull} Bull'

   
    print(cowBull)
    history[guessNum] = cowBull

print("\'YOO\' You Won the Match")
for i in history.keys():
    print(f'{i} = {history[i]}')

