# Generated by Django 4.2.15 on 2024-08-19 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(50)])),
                ('city', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=200, null=True)),
                ('read_more', models.CharField(max_length=300, null=True)),
                ('full_name', models.SlugField(default='', editable=False)),
                ('event_date', models.DateField(null=True)),
                ('event_time', models.TimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('img_title', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
