# Generated by Django 4.2.15 on 2024-08-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_detail',
            name='read_more',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
