# Generated by Django 4.2.15 on 2024-08-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_detail_city_portfolio_detail_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_detail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio_detail',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio_detail',
            name='event_time',
            field=models.TimeField(null=True),
        ),
    ]
