# Generated by Django 4.2.15 on 2024-08-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_detail_read_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_detail',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
